export const pathMap = {
  "jingqingluru":'/policeEntryList',
  "jingqingxiugai": "/policeManageEdit",
  "jingqingguanli": "/policeManageList",
  "chudongtianbao": "/dispatchReportList",
  "chudongxiugai": "/dispatchReportEdit",
  "chudongguanli": "/dispatchReportManage",
  "chudongshenhe": "/dispatchReportReview",
  'huozaitianbao': "/fire-report",
  'huozaiguanli': "/fire-manage",
  'huozaixiugai': "/fire-edit",
  'huozaishenhe':"/fire-review",
  "jingqinggengzhengshenpi": "/policeRecheckApproval",
  "jingqingzuofeishenpi": "/policeAbolishApproval",
  "chudonggengzhengshenpi": "/dispatchRecheckApproval",
  "huozaigengzhengshenpi": "/fireRecheckApproval",
  "shenqingjilu": "/applyRecord",
  "jingqingzhiliangjiandu":"/police-supervision",
  "huozaizhiliangjiandu":"/fire-supervision",
  "chudongzhiliangjiandu":'/dispatch-supervision',
  "jingqingchaoshitongji":"/police-timeout",
  "huozaichaoshitongji":"/fire-timeout",
  "chudongchaoshitongji":"/dispatch-timeout",
  "weitianbaoduizhantongji":"station-timeout"
}
  