image: beevelop/cordova:v2023.04.1

before_script:
  - node -v
  - npm -v

stages:
  - install&build
  # - upload

# cache: # 缓存
#   key: ${CI_BUILD_REF_NAME}
#   paths:
#     - foodbase-mobile/node_modules
#     - foodbase-mobile/cordova/node_modules
#     - foodbase-mobile/cordova/platforms
#     - foodbase-mobile/cordova/plugins

install&build-job:
  stage: install&build
  only:
    - /^release-.*$/
    - tags
    # - master
  tags:
    - general
  script:
    - npm install -g cordova --registry=https://mirrors.cloud.tencent.com/npm/
    - cd foodbase-mobile
    - pwd
    - npm install --registry=https://mirrors.cloud.tencent.com/npm/
    - cd cordova
    - pwd
    - npm install --registry=https://mirrors.cloud.tencent.com/npm/

    # 浙江
    - cd ../
    - DATE=`date "+%Y%m%d%H%M%S"`
    - TIMESTAMP=`date "+%s"`
    - sed -i 's|window.__appInfo = {}|window.__appInfo = {pipeLineId:'$CI_PIPELINE_ID',timestamp:'$TIMESTAMP',date:'$DATE'}|g' ./public/app.html
    - npm run build:zhejiang
    - if [[ -n "$CI_COMMIT_TAG" ]]; then
      ZHEJIANGAPKNAME="zhejiang.apk";
      ZHEJIANGAPK="../zhejiang.apk";
      ZHEJIANGVERDIONNAME="zhejiang-version.xml";
      ZHEJIANGVERDION="../zhejiang-version.xml";
      ENVTEXT="正式版";
      else
      ZHEJIANGAPKNAME="dev-zhejiang.apk";
      ZHEJIANGAPK="../dev-zhejiang.apk";
      ZHEJIANGVERDIONNAME="dev-zhejiang-version.xml";
      ZHEJIANGVERDION="../dev-zhejiang-version.xml";
      ENVTEXT="测试版";
      fi
    - echo $DATE
    - echo $TIMESTAMP
    - sed -i 's|<version>1</version>|<version>'$TIMESTAMP'</version>|g' ./public/version.xml
    - sed -i 's|<name>1.0.0</name>|<name>'$DATE'-'$TIMESTAMP'</name>|g' ./public/version.xml
    - sed -i 's|<remark>remark</remark>|<remark>'$ENVTEXT'-#'$CI_PIPELINE_ID'</remark>|g' ./public/version.xml
    - sed -i 's|<url>url</url>|<url>http://223.4.79.9:31201/foodreserver-apps/'$ZHEJIANGAPKNAME'</url>|g' ./public/version.xml
    - cd cordova
    - sed -i 's|<name>浙江储备</name>|<name>浙江储备</name>|g' config.xml
    - sed -i 's|<icon src="res/zhejiang.png"/>|<icon src="res/zhejiang.png"/>|g' config.xml
    - sed -i 's|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.foodreserves" version="1.0.0" android-versionCode="1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.zhejiang" version="'$DATE'" android-versionCode="'$TIMESTAMP'" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|g' config.xml
    # - more config.xml
    - cordova platform add android
    - cp -f ../project.properties ./platforms/android/project.properties
    - sed -i 's|cordova.gradle.include.1=phonegap-plugin-barcodescanner/foodreserves-barcodescanner.gradle|cordova.gradle.include.1=phonegap-plugin-barcodescanner/zhejiang-barcodescanner.gradle|g' ./platforms/android/project.properties
    # - more ./platforms/android/project.properties
    # - more ./platforms/android/app/build.gradle
    # - more ./plugins/cordova-base64-to-gallery/package.json
    - cordova build
    - cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $ZHEJIANGAPK
    - cp ../public/version.xml $ZHEJIANGVERDION
    - wget http://10.13.4.153:9000/foodreserver-apps/mc
    - chmod a+x mc
    - ls
    - ./mc alias set hxdi-pub http://223.4.79.9:31201/ $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - ./mc cp $ZHEJIANGAPK hxdi-pub/foodreserver-apps/$ZHEJIANGAPKNAME
    - ./mc cp $ZHEJIANGVERDION hxdi-pub/foodreserver-apps/$ZHEJIANGVERDIONNAME

    # 内蒙古
    - cd ../
    - npm run build:neimenggu
    - if [[ -n "$CI_COMMIT_TAG" ]]; then
      NEIMENGGUAPKNAME="neimenggu.apk";
      NEIMENGGUAPK="../neimenggu.apk";
      NEIMENGGUVERDIONNAME="neimenggu-version.xml";
      NEIMENGGUVERDION="../neimenggu-version.xml";
      else
      NEIMENGGUAPKNAME="dev-neimenggu.apk";
      NEIMENGGUAPK="../dev-neimenggu.apk";
      NEIMENGGUVERDIONNAME="dev-neimenggu-version.xml";
      NEIMENGGUVERDION="../dev-neimenggu-version.xml";
      fi
    - sed -i 's|<url>http://223.4.79.9:31201/foodreserver-apps/'$ZHEJIANGAPKNAME'</url>|<url>http://223.4.79.9:31201/foodreserver-apps/'$NEIMENGGUAPKNAME'</url>|g' ./public/version.xml
    - cd cordova
    - sed -i 's|<name>浙江储备</name>|<name>粮食储备</name>|g' config.xml
    - sed -i 's|<icon src="res/zhejiang.png"/>|<icon src="res/neimenggu.png"/>|g' config.xml
    - sed -i 's|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.zhejiang" version="'$DATE'" android-versionCode="'$TIMESTAMP'" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.neimenggu" version="'$DATE'" android-versionCode="'$TIMESTAMP'" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|g' config.xml
    # - more config.xml
    - rm -rf ./platforms/android/
    - cordova platform add android
    - cp -f ../project.properties ./platforms/android/project.properties
    - sed -i 's|cordova.gradle.include.1=phonegap-plugin-barcodescanner/foodreserves-barcodescanner.gradle|cordova.gradle.include.1=phonegap-plugin-barcodescanner/neimenggu-barcodescanner.gradle|g' ./platforms/android/project.properties
    # - more ./platforms/android/project.properties
    # - more ./platforms/android/app/build.gradle
    - cordova build
    - cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $NEIMENGGUAPK
    - cp ../public/version.xml $NEIMENGGUVERDION
    - ./mc cp $NEIMENGGUAPK hxdi-pub/foodreserver-apps/$NEIMENGGUAPKNAME
    - ./mc cp $NEIMENGGUVERDION hxdi-pub/foodreserver-apps/$NEIMENGGUVERDIONNAME

    # 湖北
    - cd ../
    - npm run build:hubei
    - if [[ -n "$CI_COMMIT_TAG" ]]; then
      HUBEIAPKNAME="hubei.apk";
      HUBEIAPK="../hubei.apk";
      HUBEIVERDIONNAME="hubei-version.xml";
      HUBEIVERDION="../hubei-version.xml";
      else
      HUBEIAPKNAME="dev-hubei.apk";
      HUBEIAPK="../dev-hubei.apk";
      HUBEIVERDIONNAME="dev-hubei-version.xml";
      HUBEIVERDION="../dev-hubei-version.xml";
      fi
    - sed -i 's|<url>http://223.4.79.9:31201/foodreserver-apps/'$NEIMENGGUAPKNAME'</url>|<url>http://223.4.79.9:31201/foodreserver-apps/'$HUBEIAPKNAME'</url>|g' ./public/version.xml
    - cd cordova
    - sed -i 's|<name>粮食储备</name>|<name>粮食储备</name>|g' config.xml
    - sed -i 's|<icon src="res/neimenggu.png"/>|<icon src="res/hubei.png"/>|g' config.xml
    - sed -i 's|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.neimenggu" version="'$DATE'" android-versionCode="'$TIMESTAMP'" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.hubei" version="'$DATE'" android-versionCode="'$TIMESTAMP'" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|g' config.xml
    # - more config.xml
    - rm -rf ./platforms/android/
    - cordova platform add android
    - cp -f ../project.properties ./platforms/android/project.properties
    - sed -i 's|cordova.gradle.include.1=phonegap-plugin-barcodescanner/foodreserves-barcodescanner.gradle|cordova.gradle.include.1=phonegap-plugin-barcodescanner/hubei-barcodescanner.gradle|g' ./platforms/android/project.properties
    # - more ./platforms/android/project.properties
    # - more ./platforms/android/app/build.gradle
    - cordova build
    - cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $HUBEIAPK
    - cp ../public/version.xml $HUBEIVERDION
    - ./mc cp $HUBEIAPK hxdi-pub/foodreserver-apps/$HUBEIAPKNAME
    - ./mc cp $HUBEIVERDION hxdi-pub/foodreserver-apps/$HUBEIVERDIONNAME

    # 四川
    - cd ../
    - npm run build:sichuan
    - if [[ -n "$CI_COMMIT_TAG" ]]; then
      SICHUANAPKNAME="sichuan.apk";
      SICHUANAPK="../sichuan.apk";
      SICHUANVERDIONNAME="sichuan-version.xml";
      SICHUANVERDION="../sichuan-version.xml";
      else
      SICHUANAPKNAME="dev-sichuan.apk";
      SICHUANAPK="../dev-sichuan.apk";
      SICHUANVERDIONNAME="dev-sichuan-version.xml";
      SICHUANVERDION="../dev-sichuan-version.xml";
      fi
    - sed -i 's|<url>http://223.4.79.9:31201/foodreserver-apps/'$HUBEIAPKNAME'</url>|<url>http://223.4.79.9:31201/foodreserver-apps/'$SICHUANAPKNAME'</url>|g' ./public/version.xml
    - cd cordova
    - sed -i 's|<name>粮食储备</name>|<name>天府粮仓</name>|g' config.xml
    - sed -i 's|<icon src="res/hubei.png"/>|<icon src="res/sichuan.png"/>|g' config.xml
    - sed -i 's|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.hubei" version="'$DATE'" android-versionCode="'$TIMESTAMP'" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|<widget id="com.hxid.foodreserves" android-packageName="com.hxid.sichuan" version="'$DATE'" android-versionCode="'$TIMESTAMP'" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">|g' config.xml
    # - more config.xml
    - rm -rf ./platforms/android/
    - cordova platform add android
    - cp -f ../project.properties ./platforms/android/project.properties
    - sed -i 's|cordova.gradle.include.1=phonegap-plugin-barcodescanner/foodreserves-barcodescanner.gradle|cordova.gradle.include.1=phonegap-plugin-barcodescanner/sichuan-barcodescanner.gradle|g' ./platforms/android/project.properties
    # - more ./platforms/android/project.properties
    # - more ./platforms/android/app/build.gradle
    - cordova build
    - cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $SICHUANAPK
    - cp ../public/version.xml $SICHUANVERDION
    - ./mc cp $SICHUANAPK hxdi-pub/foodreserver-apps/$SICHUANAPKNAME
    - ./mc cp $SICHUANVERDION hxdi-pub/foodreserver-apps/$SICHUANVERDIONNAME

  artifacts:
    expire_in: 4 week
    paths:
      - foodbase-mobile/zhejiang.apk
      - foodbase-mobile/zhejiang-version.xml
      - foodbase-mobile/neimenggu.apk
      - foodbase-mobile/neimenggu-version.xml
      - foodbase-mobile/hubei.apk
      - foodbase-mobile/hubei-version.xml
      - foodbase-mobile/sichuan.apk
      - foodbase-mobile/sichuan-version.xml

      - foodbase-mobile/dev-zhejiang.apk
      - foodbase-mobile/dev-zhejiang-version.xml
      - foodbase-mobile/dev-neimenggu.apk
      - foodbase-mobile/dev-neimenggu-version.xml
      - foodbase-mobile/dev-hubei.apk
      - foodbase-mobile/dev-hubei-version.xml
      - foodbase-mobile/dev-sichuan.apk
      - foodbase-mobile/dev-sichuan-version.xml
